server:
  port: 8000

spring:
  profiles: dev
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.json
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
    platform: postgres
    url: jdbc:postgresql://localhost:5432/autorizacaodb?currentSchema=autorizacao
    
  jpa:
    properties: 
      hibernate: 
        temp: 
          use_jdbc_metadata_defaults: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    hibernate:
      ddl-auto: validate
    show-sql: false  